//! `ekege-artifact` is a utility crate for storing and loading compile-time artifacts in Rust.
//! It provides a mechanism to generate and store arbitrary data during the build process
//! (typically in a [`build.rs`](https://doc.rust-lang.org/cargo/reference/build-scripts.html) script)
//! and then load that data at compile time in your main crate code.
//!
//! ## Usage
//!
//! First, implement the [`Artifact`](Artifact) trait for your custom types. Then use
//! [`store_artifact`](store_artifact) in your build script to serialize them, and [`load_artifacts!`](load_artifacts)
//! in your main code to make the constants available.
use std::{
    env,
    fs::OpenOptions,
    io::Write,
    path::PathBuf,
    sync::atomic::{self, AtomicBool},
};

/// Returns the filename used for storing artifact data.
///
/// This macro provides a consistent way to reference the artifact file
/// across the crate's public API.
#[macro_export]
macro_rules! artifact_file {
    () => {
        "ekege-artifact.rs"
    };
}

use proc_macro2::Ident;
pub use proc_macro2::TokenStream;
pub use quote::{ToTokens, TokenStreamExt, format_ident, quote};

/// A type that can be serialized as a compile-time artifact.
///
/// Implementors must be able to generate their own type representation
/// and convert themselves to a token stream.
pub trait Artifact: ToTokens {
    /// Generates a token representation of this artifact's type.
    ///
    /// This is used when storing the artifact as a typed constant.
    fn generate_type(&self) -> impl ToTokens;
}

static IS_FIRST_USE: AtomicBool = AtomicBool::new(true);

/// Stores an artifact in the build output directory.
///
/// This function writes the given artifact to a file in the build output
/// directory, making it available at compile time. The artifact is stored
/// as a Rust constant with the specified name.
///
/// # Panics
///
/// Beyond panicking upon IO errors, this function will panic when not run in a build script
/// (or if the `OUT_DIR` environment variable is otherwise unavailable).
pub fn store_artifact<A: Artifact>(name: Ident, value: A) {
    let value_type = value.generate_type();

    let is_first_use = IS_FIRST_USE.swap(false, atomic::Ordering::Acquire);

    let mut file = OpenOptions::new()
        .write(true)
        .create(true)
        .truncate(is_first_use)
        .append(!is_first_use)
        .open(PathBuf::from(env::var("OUT_DIR").expect("get OUT_DIR value")).join(artifact_file!()))
        .expect("open artifact file");
    file.write_all(
        quote! { pub const #name: #value_type = #value; }
            .to_token_stream()
            .to_string()
            .as_bytes(),
    )
    .expect("write to artifact file");
}

/// Includes all stored artifacts at compile time.
///
/// This macro includes the file generated by all [`store_artifact`] invocations,
/// making all the stored constants available in the current scope.
///
/// # Examples
///
/// In your build script:
/// ```no_run
/// store_artifact(format_ident!("BIG_TABLE"), /* ... */);
/// store_artifact(format_ident!("IMPORTANT_VALUE"), /* ... */);
/// ```
///
/// ```no_run
/// // Load all artifacts from build script
/// load_artifacts!();
///
/// println!("big table: {BIG_TABLE}, important value: {IMPORTANT_VALUE}");
/// ```
#[macro_export]
macro_rules! load_artifacts {
    () => {
        include!(concat!(env!("OUT_DIR"), "/", $crate::artifact_file!()));
    };
}
