//! General-purpose build artifact generation crate, used in [Ekege](https://docs.rs/ekege/)'s build script.
//!
//! It provides a mechanism to generate and store arbitrary data during the build process
//! (typically in a [`build.rs`](https://doc.rust-lang.org/cargo/reference/build-scripts.html) script)
//! and then load that data at compile time in your main crate code.
//!
//! # Usage
//!
//! First, implement the [`Artifact`] trait for your custom types. Then use [`store_artifact`] in your
//! build script to serialize them, and [`load_artifacts!`] in your main code to make the constants available.
//!
//! # Examples
//!
//! Given an [artifact](Artifact) `MyVec`:
//!
//! ```
//! # use ekege_artifact::{Artifact ToTokens, quote, TokenStream, TokenStreamExt};
//! #
//! struct MyVec(Vec<u16>);
//!
//! // Store `MyVec`'s data using tokens, as a build artifact
//! impl ToTokens for MyVec {
//!     fn to_tokens(&self, tokens: &mut TokenStream) {
//!         let items = &self.0;
//!
//!         tokens.append_all(quote! { [#(#items),*] });
//!     }
//! }
//!
//! // Get `MyVec`'s build artifact type, as tokens
//! impl Artifact for MyVec {
//!     fn generate_type(&self) -> impl ToTokens {
//!         let length = self.0.len();
//!
//!         quote! { [u16; #length] }
//!     }
//! }
//! ```
//!
//! We can store it using [`store_artifact`] like so:
//!
//! ```no_run
//! # use ekege_artifact::{}
//! #
//! ekege_artifact::store_artifact(
//!     format_ident!("MY_VEC"),
//!     MyVec(vec![1, 2, 3]),
//! );
//! ```
//!
//! At this point, the stored artifact will look somewhat like:
//!
//! ```
//! const MY_VEC: [u16; 3] = [1, 2, 3];
//! ```
//!
//! Using [`load_artifacts!`] we can then use that artifact in our main crate code:
//!
//! ```no_run
//! # use ekege_artifact::load_artifacts;
//! #
//! load_artifacts!();
//!
//! println!("{}", MY_VEC[0]);
//! ```
use std::{
    env,
    fs::OpenOptions,
    io::Write,
    path::PathBuf,
    sync::atomic::{self, AtomicBool},
};

/// Returns the filename used for storing artifact data.
///
/// This macro provides a consistent way to reference the artifact file
/// across the crate's public API.
///
/// Currently, the artifact file name is `ekege-artifact.rs`.
#[macro_export]
macro_rules! artifact_file {
    () => {
        "ekege-artifact.rs"
    };
}

use proc_macro2::Ident;
pub use proc_macro2::TokenStream;
pub use quote::{ToTokens, TokenStreamExt, format_ident, quote};

/// A type that can be serialized as a compile-time artifact.
///
/// Implementors must be able to generate their own type representation
/// and convert themselves to a token stream.
///
/// # Example
///
/// ```
/// # use ekege_artifact::{Artifact ToTokens, quote, TokenStream, TokenStreamExt};
/// #
/// struct MyVec(Vec<u16>);
///
/// // Store `MyVec`'s data using tokens, as a build artifact
/// impl ToTokens for MyVec {
///     fn to_tokens(&self, tokens: &mut TokenStream) {
///         let items = &self.0;
///
///         tokens.append_all(quote! { [#(#items),*] });
///     }
/// }
///
/// // Get `MyVec`'s build artifact type, as tokens
/// impl Artifact for MyVec {
///     fn generate_type(&self) -> impl ToTokens {
///         let length = self.0.len();
///
///         quote! { [u16; #length] }
///     }
/// }
/// ```
pub trait Artifact: ToTokens {
    /// Generates a token representation of this artifact's type.
    ///
    /// This is used when storing the artifact as a typed constant.
    fn generate_type(&self) -> impl ToTokens;
}

static IS_FIRST_USE: AtomicBool = AtomicBool::new(true);

/// Stores an artifact in the build output directory.
///
/// This function writes the given artifact to a file in the build output
/// directory, making it available at compile time. The artifact is stored
/// as a Rust constant with the specified name.
///
/// # Panics
///
/// Beyond panicking upon IO errors, this function will panic when not run in a build script
/// (or if the `OUT_DIR` environment variable is otherwise unavailable).
///
/// # Examples
///
/// See [this](crate) for a full usage example.
pub fn store_artifact<A: Artifact>(name: Ident, value: A) {
    let value_type = value.generate_type();

    let is_first_use = IS_FIRST_USE.swap(false, atomic::Ordering::Acquire);

    let mut file = OpenOptions::new()
        .write(true)
        .create(true)
        .truncate(is_first_use)
        .append(!is_first_use)
        .open(PathBuf::from(env::var("OUT_DIR").expect("get OUT_DIR value")).join(artifact_file!()))
        .expect("open artifact file");
    file.write_all(
        quote! { const #name: #value_type = #value; }
            .to_token_stream()
            .to_string()
            .as_bytes(),
    )
    .expect("write to artifact file");
}

/// Includes all stored artifacts at compile time.
///
/// This macro includes the file generated by all [`store_artifact`] invocations,
/// making all the stored constants available in the current scope.
///
/// # Examples
///
/// See [this](crate) for a full usage example.
#[macro_export]
macro_rules! load_artifacts {
    () => {
        include!(concat!(env!("OUT_DIR"), "/", $crate::artifact_file!()));
    };
}
