[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
ekege = { path = "./crates/ekege/" }
ekege-macros = { path = "./crates/ekege-macros" }

hashbrown = "0.14.5"

proc-macro2 = "1.0.86"
quote = "1.0.36"
syn = "2.0.67"
proc-macro-crate = "3.1.0"

[profile.release]
lto = true
codegen-units = 1
