[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
ekege = { path = "./crates/ekege/" }
ekege-macros = { path = "./crates/ekege-macros" }

indexmap = "2.2.6"
either = "1.13.0"

proc-macro2 = "1.0.86"
quote = "1.0.36"
syn = "2.0.72"
proc-macro-crate = "3.1.0"

[profile.release]
lto = true
codegen-units = 1

[profile.tests]
inherits = "dev"
opt-level = 3    # Needed for some integration tests
