[package]
name = "ekege-macros"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
hashbrown.workspace = true
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
proc-macro-crate.workspace = true
