[package]
name = "ekege"
version = "0.1.0"
edition = "2021"
description = "It's an e-graph library!"
authors = ["Yoav Grimland <miestrode@proton.me>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ekege-macros.workspace = true

bumpalo = { version = "3.16.0", features = ["allocator-api2"] }
rustc-hash = "1.1.0"
hashbrown = "0.14.5"
allocator-api2 = "0.2.18"

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }
rand = "0.8.5"

[[bench]]
name = "graph"
harness = false
