[package]
name = "ekege"
version = "0.1.0"
description = "An E-graph library that's built like a database"
keywords = ["e-graphs", "eqsat", "egglog", "datalog", "equality"]
categories = ["database-implementations", "data-structures"]
authors = ["Yoav Grimland <miestrode@proton.me>"]
rust-version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[lints]
workspace = true

[dependencies]
# Workspace members
ekege-macros.workspace = true
ekege-artifact.workspace = true

# Regular dependencies
rustc-hash.workspace = true
hashbrown.workspace = true
bitfield-struct.workspace = true
cranelift.workspace = true
cranelift-jit.workspace = true

[dev-dependencies]
divan.workspace = true
rand.workspace = true

[build-dependencies]
# Workspace members
ekege-artifact.workspace = true

# Regular dependencies
rand.workspace = true
rand_chacha.workspace = true

[[bench]]
name = "graph"
harness = false
