[package]
name = "ekege"
version = "0.1.0"
edition = "2021"
description = "An alternative egglog engine"
authors = ["Yoav Grimland <miestrode@proton.me>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ekege-macros.workspace = true

hashbrown.workspace = true
mimalloc.workspace = true

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }
rand = "0.8.5"

[[bench]]
name = "graph"
harness = false
