[package]
name = "ekege"
version = "0.1.0"
edition = "2021"
description = "An alternative egglog engine"
authors = ["Yoav Grimland <miestrode@proton.me>"]

[dependencies]
ekege-macros.workspace = true

indexmap.workspace = true
either.workspace = true
rustc-hash.workspace = true

[dev-dependencies]
criterion.workspace = true
rand.workspace = true

[[bench]]
name = "graph"
harness = false
